### ISSUE TITLE
Doesn't work on Google App Engine

### ISSUE THREAD

**Issue by rs** [alimanfoo/petl#245]
When petl is used on app engine, the `io` module cries because some dependencies can't be resolved. GAE doesn't support C modules, thus it's not possible to install sqlite for instance, and it doesn't make sens to install such module when not used.

What about extracting all sqlalchemy and sqlite functions from io.py and make sure the __init__.py doesn't import them automatically?

**Comment by alimanfoo** [comment]
Imports of sqlite3, cStringIO and cPickle are all now conditional or hidden in v1.0, so petl *should* work on GAE, but feel free to re-open if any problems arise.
