### ISSUE TITLE
Showing Source of Conflict

### ISSUE THREAD

**Issue by pawl** [alimanfoo/petl#256]
I'm using mergeduplicates to combine data from two spreadsheets and show the cells with discrepancies. I want the cells with discrepancies to show "Source1: value1,   Source2: value2" rather than the unordered Conflict((value2,value1)). 

When a conflict occurs, is there a way to determine the source of the conflict after I've done petl.cat on the data and performed petl.mergeduplicates?

One possibility might be to use petl.conflicts and add a column showing the source to each table? But, I prefer having the duplicates merged for readability purposes.

**Comment by alimanfoo** [comment]
Closing as can be worked around, however happy to review revised PR if anyone needs this functionality within mergeduplicates.

**Comment by shaunagm** [comment]
Running into this issue, but alas the jupyter notebook with the workaround is no longer there. Any advice for the best way to handle this? I'm trying to figure out the most effective way to resolve conflicts in rows that need to be merged, using information from a different column (the other column is a timestamp column—I'm trying to keep the most recently updated value).

**Comment by shaunagm** [comment]
Thanks @bmaggard! I guess I already knew the workaround. :)

Ideally, I'd love to see something like `mergeduplicates(key, optional_conflict_resolution_function)` where the optional function would take in the equivalent of the two (or I guess 2+) rows of the conflict table as well as the column being dealt with (since the function would have to be applied column by column on two rows in conflict). Like:

`def conflict_resolution_function(column_name, conflicting_rows=[]):
  return final_value_for_cell`

This is less a feature request since that seems like a lot of work to add if you don't have it already, and more of a "this would be really nice, maybe I've misunderstood your docs and you already have something like it?"

**Comment by bmaggard** [comment]
### re: "keeping the most recently updated value"
For an arbitrary number of tables with arbitrary sets of columns, but with keys in common, I'd not use any of the difference methods, and instead do something along the lines of:
- melt() them all by key and timestamp, 
- pick most recent value (aggregate())
- recast() the cat() of the results

as always, YMMV with large datasets

### re: the original problem of "show the cells with discrepancies"
I use `daff` for displaying differences between tables: https://pypi.org/project/daff/

I've tried to produce the daff reports directly from `petl` tables, but the python version is too slow, so my preferred technique is to export to tsv and compare with somehting like:
`daff --id 1 --input-format tsv -www 1.tsv 2.tsv`

**Comment by fjuniorr** [comment]
> I'm trying to figure out the most effective way to resolve conflicts in rows that need to be merged, using information from a different column (the other column is a timestamp column—I'm trying to keep the most recently updated value).

@shaunagm just needed this myself and ended up reaching to [rowgroupmap](https://petl.readthedocs.io/en/stable/transform.html#petl.transform.maps.rowgroupmap). Something like:

```python
import petl

tbl = petl.wrap([
    ('id', 'name', 'value', 'timestamp'),
    (1, 'Alice', 10, '2024-01-01'),
    (1, 'Alice', 15, '2024-01-04'),
    (1, 'Alice', 50, '2024-01-05'),
    (2, 'Bob', 20, '2024-01-02'),
    (2, 'Bob', 25, '2024-01-01'),
    (3, 'Charlie', 30, '2024-01-01'),
    (3, 'Charlie', 35, '2024-01-05'),
])

def rowmap(key, rows):
    result = max(rows, key=lambda row: row["timestamp"])
    yield result

result = petl.rowgroupmap(tbl, key=["id"], mapper=rowmap, header=tbl.header())

result.lookall()
# +----+-----------+-------+--------------+
# | id | name      | value | timestamp    |
# +====+===========+=======+==============+
# |  1 | 'Alice'   |    50 | '2024-01-05' |
# +----+-----------+-------+--------------+
# |  2 | 'Bob'     |    20 | '2024-01-02' |
# +----+-----------+-------+--------------+
# |  3 | 'Charlie' |    35 | '2024-01-05' |
# +----+-----------+-------+--------------+
```
