### ISSUE TITLE
on Windows, sorts of large tables error out due to Permission Denied

### ISSUE THREAD

**Issue by rogerkwoodley** [alimanfoo/petl#278]
On Windows **only**, sorts of sufficiently large tables errors out due to ```IOError: [Errno 13] Permission denied```

The error occurs when the number of rows in the table exceeds ```petl.transform.defaultbuffersize``` (default=100,000), and petl relies on temp files.

This is caused by a [known issue in Python and Windows](https://docs.python.org/2/library/tempfile.html#tempfile.NamedTemporaryFile), and thus is not readily solved by us.

A hack I've employed is to add the ```delete=False``` argument [when NamedTemporaryFile is instantiated](https://github.com/alimanfoo/petl/blob/master/src/petl/transform/sorts.py#L250).  However, the temporary file(s) will not be deleted automatically when the files are no longer needed.

I'm working on a way to handle this situation without changing defaultbuffersize.

**Comment by alimanfoo** [comment]
This should now be fixed in v1.0 branch, which includes some tests to ensure that cleanup of temporary files happens when objects are garbage collected.
