### ISSUE TITLE
regexp itersearch expects ascii string and chokes on unicodes

### ISSUE THREAD

**Issue by cons0l3** [alimanfoo/petl#294]
Hi,

I have a table staged in a sqlite with unicode strings. Running a petl.search or petl.searchcomplement with regexp on it throws the exception:
`File "C:\Python27\lib\site-packages\petl\transform\regex.py", line 342, in <lambda>
    test = lambda row: prog.search(str(row[index]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 12: ordinal not in range(128)`

I solution could be replace the `str` with a `unicode` conversion in lines 342 and 347. I believe `unicode` is a superset of `str` and should convert any possible string correctly. As it is only required for `test` and not exposed externally the unicode conversion is permissable.

Cheers
Carsten

**Comment by alimanfoo** [comment]
fixed in v1.0
