### ISSUE TITLE
Whoosh example is not working...

### ISSUE THREAD

**Issue by stancikcom** [alimanfoo/petl#313]
Hi guys,

seems that the Petl - Whoosh adapter seems not to work, or I do not know where I do a mistake.

Tested on:
* Python 2.7.4  32-bit
* Petl version 1.0.4
* Whoosh version 2.2.2

with the following code (taken from Petl manual)
```
import petl as etl
# set up an index and load some documents via the Whoosh API
from whoosh.index import create_in
from whoosh.fields import *

print whoosh.__version__
print etl.__version__

schema = Schema(title=TEXT(stored=True), path=ID(stored=True), content=TEXT)

dirname = "example.whoosh"
if not os.path.exists(dirname):
	os.mkdir(dirname)

index = create_in(dirname, schema)
writer = index.writer()
writer.add_document(title=u"First document", path=u"/a", content=u"This is the first document we’ve added!")
writer.add_document(title=u"Second document", path=u"/b", content=u"The second one is even more interesting!")
writer.commit()

# extract documents as a table
table = etl.fromtextindex(dirname)
print type(table)
print repr(table)
```
ends with following exception:
```
(2, 2, 2)
1.0.4
<class 'petl.io.whoosh.TextIndexView'>
Traceback (most recent call last):
  File "C:\Python27\mywhoo2.py", line 38, in <module>
    print repr(table)
  File "C:\Python27\lib\site-packages\petl\util\vis.py", line 135, in _table_repr
    return str(look(table))
  File "C:\Python27\lib\site-packages\petl\util\vis.py", line 104, in __repr__
    table, overflow = _vis_overflow(self.table, self.limit)
  File "C:\Python27\lib\site-packages\petl\util\vis.py", line 528, in _vis_overflow
    table = list(islice(table, 0, limit+2))
  File "C:\Python27\lib\site-packages\petl\io\whoosh.py", line 102, in itertextindex
    for _, stored_fields_dict in index.reader().iter_docs():
AttributeError: 'SegmentReader' object has no attribute 'iter_docs'
```

**Comment by alimanfoo** [comment]
Thanks Martin, I'll take a look.

On Friday, 6 February 2015, Martin Stancik <notifications@github.com> wrote:

> Hi guys,
>
> seems that the Petl - Whoosh adapter seems not to work, or I do not know
> where I do a mistake.
>
> Tested on:
>
>    - Python 2.7.4 32-bit
>    - Petl version 1.0.4
>    - Whoosh version 2.2.2
>
> with the following code (taken from Petl manual)
>
> import petl as etl
> # set up an index and load some documents via the Whoosh API
> from whoosh.index import create_in
> from whoosh.fields import *
>
> print whoosh.__version__
> print etl.__version__
>
> schema = Schema(title=TEXT(stored=True), path=ID(stored=True), content=TEXT)
>
> dirname = "example.whoosh"
> if not os.path.exists(dirname):
>     os.mkdir(dirname)
>
> index = create_in(dirname, schema)
> writer = index.writer()
> writer.add_document(title=u"First document", path=u"/a", content=u"This is the first document we've added!")
> writer.add_document(title=u"Second document", path=u"/b", content=u"The second one is even more interesting!")
> writer.commit()
>
> # extract documents as a table
> table = etl.fromtextindex(dirname)
> print type(table)
> print repr(table)
>
> ends with following exception:
>
> (2, 2, 2)
> 1.0.4
> <class 'petl.io.whoosh.TextIndexView'>
> Traceback (most recent call last):
>   File "C:\Python27\mywhoo2.py", line 38, in <module>
>     print repr(table)
>   File "C:\Python27\lib\site-packages\petl\util\vis.py", line 135, in _table_repr
>     return str(look(table))
>   File "C:\Python27\lib\site-packages\petl\util\vis.py", line 104, in __repr__
>     table, overflow = _vis_overflow(self.table, self.limit)
>   File "C:\Python27\lib\site-packages\petl\util\vis.py", line 528, in _vis_overflow
>     table = list(islice(table, 0, limit+2))
>   File "C:\Python27\lib\site-packages\petl\io\whoosh.py", line 102, in itertextindex
>     for _, stored_fields_dict in index.reader().iter_docs():
> AttributeError: 'SegmentReader' object has no attribute 'iter_docs'
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/313>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by stancikcom** [comment]
After upgrade of Whoosh on actual stable version 2.5.7,
all works smoothly, I assume that the problem was that 
older version of Whoosh had different API.

Suggestion: Consider to insert into PETL adapter a Whoosh version check / warning.


```
(2, 5, 7)
1.0.4
<class 'petl.io.whoosh.TextIndexView'>
+-------+--------------------+
| path  | title              |
+=======+====================+
| u'/a' | u'First document'  |
+-------+--------------------+
| u'/b' | u'Second document' |
+-------+--------------------+```

**Comment by alimanfoo** [comment]
Thanks Martin, I'll add a version check.

On Thu, Feb 19, 2015 at 9:48 AM, Martin Stancik <notifications@github.com>
wrote:

> After upgrade of Whoosh on actual stable version 2.5.7,
> all works smoothly, I assume that the problem was that
> older version of Whoosh had different API.
>
> Suggestion: Consider to insert into PETL adapter a Whoosh version check /
> warning.
>
> (2, 5, 7)
> 1.0.4
> <class 'petl.io.whoosh.TextIndexView'>
> +-------+--------------------+
> | path  | title              |
> +=======+====================+
> | u'/a' | u'First document'  |
> +-------+--------------------+
> | u'/b' | u'Second document' |
> +-------+--------------------+```
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/313#issuecomment-75023325>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by stancikcom** [comment]
I had recently problem with openpyxl module. It raised an Exception 
After following discussion here:  http://stackoverflow.com/questions/23639550/how-to-read-a-long-excel-file-using-openpyxl 
after an update of openpyxl into new version, now the PETL works well. However with new version an another application (using PANDAS) is failing now :-/ 

As there is no control about dependencies modules, I would besides version check consider an adapter that will help reliability with legacy APIs versions.

**Comment by stancikcom** [comment]
I looked around and it is not easy to have solid "version checking", as not 100% modules are using `.__version__` attribute.

In order to have something more generic, I propose following helper functions that either return a module version (as it is read by distilutils), or in case when optional arguments (min_version, max_version) a boolean value as result of evaluation.

Let me know if you like the idea ...

```python
def get_version( module ):
	import pkg_resources
	try:
		version = map(int,pkg_resources.get_distribution(module).version.split(".")) 
	except pkg_resources.DistributionNotFound, e:
		# print e
		return None
	return version

def check_version(module_name,min_version=None,max_version=None):
	if min_version and max_version:
		return min_version < get_version(module_name) < max_version
	if min_version and not max_version:
		return min_version < get_version(module_name)
	if max_version:
		return get_version(module_name) < max_version
	return get_version(module_name)

print get_version("openpyxl")
print check_version("openpyxl",max_version = [1,3,1])
print check_version("whoosh")
print check_version("whoosh", [1,2,0])
print check_version("whoosh", [1,2,0],[2,5,0])
```
which gives a following output:
```python
[1, 8, 6]
False
[2, 6, 0]
True
False
```

**Comment by alimanfoo** [comment]
Hi Martin, thanks for looking into this. If it works on all platforms then
it sounds fine to me.

On Tue, Mar 17, 2015 at 3:32 PM, Martin Stancik <notifications@github.com>
wrote:

> I looked around and it is not easy to have solid "version checking", as
> not 100% modules are using .__version__ attribute.
>
> In order to have something more generic, I propose following helper
> functions that either return a module version (as it is read by
> distilutils), or in case when optional arguments (min_version, max_version)
> a boolean value as result of evaluation.
>
> Let me know if you like the idea ...
>
> def get_version( module ):
>     import pkg_resources
>     try:
>         version = map(int,pkg_resources.get_distribution(module).version.split("."))
>     except pkg_resources.DistributionNotFound, e:
>         # print e
>         return None
>     return version
> def check_version(module_name,min_version=None,max_version=None):
>     if min_version and max_version:
>         return min_version < get_version(module_name) < max_version
>     if min_version and not max_version:
>         return min_version < get_version(module_name)
>     if max_version:
>         return get_version(module_name) < max_version
>     return get_version(module_name)
> print get_version("openpyxl")print check_version("openpyxl",max_version = [1,3,1])print check_version("whoosh")print check_version("whoosh", [1,2,0])print check_version("whoosh", [1,2,0],[2,5,0])
>
> which gives a following output:
>
> [1, 8, 6]False
> [2, 6, 0]TrueFalse
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/313#issuecomment-82415946>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by stancikcom** [comment]
1. Which 'all' platforms  it should support? 

2. Maintain legacy adapters for all possible combinations might be too expensive... Perhaps would be sufficient to shadow external modules into `try - except` sandbox and perform version check only in case an API related exception is cought.  I already have few ideas for a generic solution.

3. I still consider is worth to maintain legacy adapter / cross-check against  a "dependency hell" with the latest versions of petl's optional modules.

**Comment by alimanfoo** [comment]
Hi Martin,

On Wednesday, 18 March 2015, Martin Stancik <notifications@github.com>
wrote:

>
>    1.
>
>    Which 'all' platforms it should support?
>
> I currently test under Linux (Ubuntu 14.10) and Windows 7, under Python
2.6, 2.7 and 3.4.
>
>
>    1.
>
>    Maintain legacy adapters for all possible combinations might be too
>    expensive... Perhaps would be sufficient to shadow external modules into try
>    - except sandbox and perform version check only in case an API related
>    exception is cought. I already have few ideas for a generic solution.
>
> For the optional dependencies, if you have the time to write a legacy
adapter then I'm all for it. However if you're worried about maintenance
effort then I'm happy to only support some subset of versions with a
consistent API. N.b., if we do want to support multiple versions of a
dependency across some API change then we should probably add another test
environment to the tox setup to ensure coverage.

>
>    1.
>
>    I still consider is worth to maintain legacy adapter / cross-check
>    against a "dependency hell" with the latest versions of petl's optional
>    modules.
>
> See comment above.

Cheers,
Alistair

>
>    1.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/313#issuecomment-82880527>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by stancikcom** [comment]
Update.  The 'dependency issue' is not that hot anymore. After upgrade of `pandas` to version 0.16.0, same versions of `openpyxl` are supported... Nevertheless, despite a lower priority, improved exception / debugging / testing of dependency modules it is still on my tasklist to address.
cheers. (ms)

**Comment by alimanfoo** [comment]
Thanks Martin, if you do get a chance to do any work on dependency handling
I'd be very happy to include it.

On Thursday, 2 April 2015, Martin Stancik <notifications@github.com> wrote:

> Update. The 'dependency issue' is not that hot anymore. After upgrade of
> pandas to version 0.16.0, same versions of openpyxl are supported...
> Nevertheless, despite a lower priority, improved exception / debugging /
> testing of dependency modules it is still on my tasklist to address.
> cheers. (ms)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/313#issuecomment-88798764>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
I'm going to close this issue but feel free to re-open and/or issue a PR if you want to contribute some dependency-checking support.
