### ISSUE TITLE
Insert into Oracle

### ISSUE THREAD

**Issue by developer999** [alimanfoo/petl#314]
Hello,

thank you for your good job.
I try to insert into Oracle table,  I do not know where I do a mistake.
Could you please advise me?
Thanks in advance.

Python 3.4.2
Petl version 1.0.4
cx_Oracle-5.1.3-12c.win-amd64-py3.4

My code:

import cx_Oracle
import petl as etl
connection = 'DEV/DEV@ORCL'
orcl = cx_Oracle.connect(connection)
table = etl.fromdb(orcl, 'SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM dba_objects')
etl.todb(table=table,dbo= orcl,tablename='MYTEST123')

I receive following error:
C:\Apps\Python34\python.exe C:/Python/Workspace/Project1/Test.py
Traceback (most recent call last):
  File "C:/Python/Workspace/Project1/Test.py", line 8, in <module>
    etl.todb(table=table,dbo= orcl,tablename='MYTEST123')
  File "C:\Apps\Python34\lib\site-packages\petl\io\db.py", line 300, in todb
    truncate=True)
  File "C:\Apps\Python34\lib\site-packages\petl\io\db.py", line 319, in _todb
    commit=commit, truncate=truncate)
  File "C:\Apps\Python34\lib\site-packages\petl\io\db.py", line 396, in _todb_dbapi_connection
    cursor.executemany(insertquery, it)
TypeError: must be list, not generator

Process finished with exit code 1

I have destination table:

CREATE TABLE MYTEST123
(
  OWNER        VARCHAR2(128 BYTE),
  OBJECT_NAME  VARCHAR2(128 BYTE),
  OBJECT_TYPE  VARCHAR2(23 BYTE)
)

VIEW dba_objects
 Name                                      Null?    Type                        
 ----------------------------------------- -------- ----------------------------
 OWNER                                              VARCHAR2(128)               
 OBJECT_NAME                                  VARCHAR2(128)               
 OBJECT_TYPE                                   VARCHAR2(23)

**Comment by alimanfoo** [comment]
Hi, apologies I didn't reply earlier. FWIW I hit a similar problem recently when trying to use the official MySQL connector, for some reason the connector implementation checked for the presence of a list and wouldn't accept an iterator, which seems crazy and pointless to me. Anyway, I switched to a different connector (pymysql) and it worked fine, so if you have the option of trying a different connector, that's the only thing I can suggest (apart from materialising the whole petl table as a list, which is undesirable for large tables).

**Comment by gotgenes** [comment]
This is actually not a bug in pet. It is [a bug in the cx_Oracle driver, in which their `Cursor.executemany` is hard coded to accept only a list of parameters to insert, rather than supporting iterables in general](https://bitbucket.org/anthony_tuininga/cx_oracle/issue/13/cursorexecutemany-should-accept-iterators).
