### ISSUE TITLE
Bug in db_create.py

### ISSUE THREAD

**Issue by developer999** [alimanfoo/petl#317]
Hello,

I found bad command for oracle dialect in the file db_create.py
When I used the following command (db is SqlAlchemy engine):
etl.todb(table=table,dbo=db,tablename='TEST',create=True,drop=True,dialect='oracle')
this failed, because generated drop SQL script is not valid for Oracle database

in the file db_create.py is following line:
sql = u'DROP TABLE IF EXISTS %s;' % tablename

but Oracle doesn't support IF EXIST clause.

and there is another issue from Oracle point of view. In the file db_create.py is following line:

    return text_type(sqlalchemy.schema.CreateTable(sql_table)
                     .compile(dialect=sql_dialect)).strip() + ';'

The issue is semicolon at the end of line , this semicolon caused that created SQL command failed in Oracle database.

Best regards

Paul

**Comment by alimanfoo** [comment]
Hi Paul,

Thanks for reporting this, much appreciated.

Do you know if there is any alternative to "IF EXISTS" in Oracle?

On Sunday, March 1, 2015, developer999 <notifications@github.com> wrote:

> Hello,
>
> I found bad command for oracle dialect in the file db_create.py
> When I used the following command (db is SqlAlchemy engine):
>
> etl.todb(table=table,dbo=db,tablename='TEST',create=True,drop=True,dialect='oracle')
> this failed, because generated drop SQL script is not valid for Oracle
> database
>
> in the file db_create.py is following line:
> sql = u'DROP TABLE IF EXISTS %s;' % tablename
>
> but Oracle doesn't support IF EXIST clause.
>
> and there is another issue from Oracle point of view. In the file
> db_create.py is following line:
>
> return text_type(sqlalchemy.schema.CreateTable(sql_table)
>                  .compile(dialect=sql_dialect)).strip() + ';'
>
> The issue is semicolon at the end of line , this semicolon caused that
> created SQL command failed in Oracle database.
>
> Best regards
>
> Paul
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/317>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by developer999** [comment]
Hi Alistair,

I found this link with detailed explanation http://ora-exp.blogspot.cz/2013/03/oracle-drop-table-if-exists.html

I think the sufficient option is to use anonymous block:
 BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TABLE_NAME';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE <> -942 THEN
      RAISE;
    END IF;
END;

the SQLCODE 942 is exception when table doesn't exists, all others exceptions will be propagated
ORA-00942:	table or view does not exist

Best regards,

Paul

**Comment by alimanfoo** [comment]
Thanks Paul, much appreciated. I'll give some thought to how best to
incorporate this.

On Mon, Mar 2, 2015 at 7:22 PM, developer999 <notifications@github.com>
wrote:

> Hi Alistair,
>
> I found this link with detailed explanation
> http://ora-exp.blogspot.cz/2013/03/oracle-drop-table-if-exists.html
>
> I think the sufficient option is to use anonymous block:
> BEGIN
> EXECUTE IMMEDIATE 'DROP TABLE TABLE_NAME';
> EXCEPTION
> WHEN OTHERS THEN
> IF SQLCODE <> -942 THEN
> RAISE;
> END IF;
> END;
>
> the SQLCODE 942 is exception when table doesn't exists, all others
> exceptions will be propagated
> ORA-00942: table or view does not exist
>
> Best regards,
>
> Paul
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/317#issuecomment-76789623>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Hi @developer999, sorry for long silence on this. 

Regarding the IF EXISTS problem, I think I would propose to just remove the "IF EXISTS" for all databases. This should be acceptable, as the default for the `drop` argument is False, so in general a user has to actively choose to try and drop the DB. So if the user attempts to drop a non-existent database and gets an error, that's reasonable.

Regarding the trailing semicolon problem, I'll investigate whether removing this causes any problems with mysql or postegres.
