### ISSUE TITLE
Petl 1.0.6 - fromdb returning multiple rows from mysql table with only one row in it

### ISSUE THREAD

**Issue by markjdev** [alimanfoo/petl#325]
I've hit a problem where using fromdb returns 2 rows for a table in MySQL that only contains 1 row. I've included sample SQL below to create a demo table and code to show the issue.

SQL

create table petl_error(
	id int not null primary key,
	value varchar(20) not null
);

insert into petl_error (id, value) values(1, 'Hello World');

select * from petl_error;

CODE
import MySQLdb
import petl

connection = MySQLdb.connect(host='localhost', db='test', user='user', passwd='password')

table = petl.fromdb(connection, 'SELECT id, value from petl_error;')

print "%d rows" % petl.nrows(table)

print petl.look(table)

OUTPUT
2 rows
+----+---------------+
| id | value         |
+====+===============+
| 1L | 'Hello World' |
+----+---------------+
| 1L | 'Hello World' |
+----+---------------+

**Comment by alimanfoo** [comment]
Thanks for reporting, very strange. I'll try to reproduce.

On Wednesday, 8 April 2015, markjdev <notifications@github.com> wrote:

> I've hit a problem where using fromdb returns 2 rows for a table in MySQL
> that only contains 1 row. I've included sample SQL below to create a demo
> table and code to show the issue.
>
> SQL
>
> create table petl_error(
> id int not null primary key,
> value varchar(20) not null
> );
>
> insert into petl_error (id, value) values(1, 'Hello World');
>
> select * from petl_error;
>
> CODE
> import MySQLdb
> import petl
>
> connection = MySQLdb.connect(host='localhost', db='test', user='user',
> passwd='password')
>
> table = petl.fromdb(connection, 'SELECT id, value from petl_error;')
>
> print "%d rows" % petl.nrows(table)
>
> print petl.look(table)
>
> OUTPUT
> 2 rows
> +----+---------------+
> | id | value |
> +====+===============+
> | 1L | 'Hello World' |
> +----+---------------+
> | 1L | 'Hello World' |
> +----+---------------+
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/325>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Fix included in release 1.0.9.
