### ISSUE TITLE
Set operation does not handle duplicate rows

### ISSUE THREAD

**Issue by christippett** [alimanfoo/petl#333]
Forgive me if this is the intended result, but it appears as though the set operation (complement(), intersection(), et. al) does not take into consideration the occurrence of duplicate rows.

Using an updated example from the documentation:

    >>> import petl as etl
    >>> a = [['foo', 'bar', 'baz'],
    ...     ['A', 1, True],
    ...     ['C', 7, False],
    ...     ['B', 2, False],
    ...     ['C', 9, True],
    ...     ['C', 9, True]]
    >>> b = [['x', 'y', 'z'],
    ...     ['B', 2, False],
    ...     ['A', 9, False],
    ...     ['B', 3, True],
    ...     ['C', 9, True]]
    >>> aminusb = etl.complement(a, b)
    >>> aminusb
    +-----+-----+-------+
    | foo | bar | baz   |
    +=====+=====+=======+
    | 'A' |   1 | True  |
    +-----+-----+-------+
    | 'C' |   7 | False |
    +-----+-----+-------+
    | 'C' |   9 | True  |
    +-----+-----+-------+

I would have thought that both occurrences of `['C', 9, True]` should be excluded from the resulting table?

`petl.transform.dedup.duplicates` does not apply for my particular use case, otherwise I would just apply this before applying the set operation.

**Comment by alimanfoo** [comment]
Sincere apologies for leaving this hanging for so many months. For the record, I made a deliberate change way back to the behaviour of complement() with duplicate rows in response to #2 (originally discussed in #1). This was to make the diff() function behave as expected by users. So the current behaviour is intended.

It would be possible to add an option to complement to make it a strict set-like operation. I think I will do this to make the default behaviour clear for users.

**Comment by alimanfoo** [comment]
Working on this.

**Comment by christippett** [comment]
Thanks for looking into this. An option for a strict set-like operation sounds great, I'm sure there'd be cases where users would want both types of functionality (I'd certainly appreciate it).
