### ISSUE TITLE
totsv() output of None value changed from empty string to "None"

### ISSUE THREAD

**Issue by psnj** [alimanfoo/petl#335]
Not sure if this is a bug or an intentional change, but it was not certainly something I expected, or saw mentioned in the changelog.

In PETL 0.26 (Python 2.6 or 2.7):

    petl.totsv([('fld',), (None,)], 'file.tsv')

produces a file containing:

    fld
    ""

whereas in PETL 1.0 it produces:

    fld
    None

(PETL is awesome, btw!)

**Comment by alimanfoo** [comment]
Thanks @psnj, there was a PR to fix this in #328, I'm at a conference this week but will track down what happened to that ASAP.

**Comment by psnj** [comment]
Thanks @alimanfoo. Sorry, I didn't see an Issue around this, but I should have checked PRs as well.

**Comment by alimanfoo** [comment]
No problem, thanks for taking the time to report. I think that PR is still
pending so will get it merged asap.

On Monday, 8 June 2015, Paul Jensen <notifications@github.com> wrote:

> Thanks @alimanfoo <https://github.com/alimanfoo>. Sorry, I didn't see an
> Issue around this, but I should have checked PRs as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/335#issuecomment-110161097>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Released in v1.0.11.
