### ISSUE TITLE
contents go missing when loading a generator using .fromdicts()

### ISSUE THREAD

**Issue by thatneat** [alimanfoo/petl#341]
input:
```python
>>> petl.fromdicts(row for row in [{'foo':1,'bar':2},{'foo':3,'bar':4}]).tocsv()
```
expected output:
```
bar,foo
1,2
3,4
```
actual output (only the header survives!):
```
bar,foo
```

**Comment by thatneat** [comment]
sorry for all the branches; the last one (e2f9f3e) is the one I recommend merging in.

**Comment by alimanfoo** [comment]
Many thanks @thatneat, I'll take a look asap.

On Wednesday, September 9, 2015, thatneat <notifications@github.com> wrote:

> sorry for all the branches; the last one (e2f9f3e
> <https://github.com/alimanfoo/petl/commit/e2f9f3e83f16289629ad82186a0baaafedde21ea>)
> is the one I recommend merging in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/341#issuecomment-138986017>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Working on this now...
