### ISSUE TITLE
Joining to a table that has no non-key fields raises 'AssertionError: indices is empty'

### ISSUE THREAD

**Issue by bmaggard** [alimanfoo/petl#345]
Urgency: LOW
Error Message: "AssertionError: indices is empty"
Code Snippet:
Suggestion: Joins between tables that contain only key columns should work.

```python
# petl v1.0.11
import petl as etl

c = [['id','val'],[20,1],[3,1],[6,1],[12,1],[15,1]]
u = [['id','val'],[3,2],[6,2],[9,2],[12,2],[15,2]]
etl.join(c,u,key='id')

+----+-----+-----+
| id | val | val |
+====+=====+=====+
|  3 |   1 |   2 |
+----+-----+-----+
|  6 |   1 |   2 |
+----+-----+-----+
| 12 |   1 |   2 |
+----+-----+-----+
| 15 |   1 |   2 |
+----+-----+-----+

u = etl.cut(u,'id')
etl.join(c,u,key='id')

...

/tank/etl/anaconda3/lib/python3.4/site-packages/petl/util/base.py in
rowgetter(*indices)
    308
    309     # guard condition
--> 310     assert len(indices) > 0, 'indices is empty'
    311
    312     # if only one index, we cannot use itemgetter, because we
want a singleton

AssertionError: indices is empty
```

**Comment by alimanfoo** [comment]
Thanks for raising the issue, will put on the list for next release.

On Thursday, October 8, 2015, bmaggard <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Urgency: LOW
> Error Message: "AssertionError: indices is empty"
> Code Snippet:
> Suggestion: Joins between tables that contain only key columns should work.
>
> # petl v1.0.11import petl as etl
>
> c = [['id','val'],[20,1],[3,1],[6,1],[12,1],[15,1]]
> u = [['id','val'],[3,2],[6,2],[9,2],[12,2],[15,2]]
> etl.join(c,u,key='id')
> +----+-----+-----+| id | val | val |+====+=====+=====+|  3 |   1 |   2 |+----+-----+-----+|  6 |   1 |   2 |+----+-----+-----+| 12 |   1 |   2 |+----+-----+-----+| 15 |   1 |   2 |+----+-----+-----+
>
> u = etl.cut(u,'id')
> etl.join(c,u,key='id')
>
> ...
> /tank/etl/anaconda3/lib/python3.4/site-packages/petl/util/base.py in
> rowgetter(*indices)
>     308
>     309     # guard condition--> 310     assert len(indices) > 0, 'indices is empty'
>     311
>     312     # if only one index, we cannot use itemgetter, because we
> want a singleton
> AssertionError: indices is empty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/345>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721
