### ISSUE TITLE
can not look the return result with fromcsv?

### ISSUE THREAD

**Issue by Alwayslow** [alimanfoo/petl#347]
windows 7 32bit   python 2.7.10
>>> import csv
>>> with open('test.csv', 'wb') as f:
        writer = csv.writer(f)
        writer.writerow(['foo', 'bar'])
        writer.writerow(['a', 1])
        writer.writerow(['b', 2])
        writer.writerow(['c', 2])

>>> from petl import fromcsv, look
>>> testcsv = fromcsv('test.csv')
>>> look(testcsv)

Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    look(testcsv)
  File "D:\ProgramFiles\python27\lib\site-packages\petl\util\vis.py", line 104, in __repr__
    table, overflow = _vis_overflow(self.table, self.limit)
  File "D:\ProgramFiles\python27\lib\site-packages\petl\util\vis.py", line 528, in _vis_overflow
    table = list(islice(table, 0, limit+2))
  File "D:\ProgramFiles\python27\lib\site-packages\petl\io\csv_py2.py", line 44, in __iter__
    errors=self.errors, **self.csvargs)
  File "D:\ProgramFiles\python27\lib\site-packages\petl\io\csv_py2.py", line 145, in __init__
    f = UTF8Recoder(f, encoding=encoding, errors=errors)
  File "D:\ProgramFiles\python27\lib\site-packages\petl\io\csv_py2.py", line 133, in __init__
    self.reader = codec.streamreader(buf, errors=errors)
TypeError: StreamReader() argument 2 must be string, not None

**Comment by alimanfoo** [comment]
Thanks for the bug report, I'll look into it.

On Thu, Oct 22, 2015 at 6:07 AM, Alwayslow <notifications@github.com> wrote:

> windows 7 32bit python 2.7.10
>
> import csv
> with open('test.csv', 'wb') as f:
> writer = csv.writer(f)
> writer.writerow(['foo', 'bar'])
> writer.writerow(['a', 1])
> writer.writerow(['b', 2])
> writer.writerow(['c', 2])
>
> from petl import fromcsv, look
> testcsv = fromcsv('test.csv')
> look(testcsv)
>
> Traceback (most recent call last):
> File "", line 1, in
> look(testcsv)
> File "D:\ProgramFiles\python27\lib\site-packages\petl\util\vis.py", line
> 104, in *repr*
> table, overflow =
>
>
> *vis_overflow(self.table, self.limit) File
> "D:\ProgramFiles\python27\lib\site-packages\petl\util\vis.py", line 528, in
> vis_overflow table = list(islice(table, 0, limit+2)) File
> "D:\ProgramFiles\python27\lib\site-packages\petl\io\csv_py2.py", line 44,
> in __iter*
> errors=self.errors, **self.csvargs)
> File "D:\ProgramFiles\python27\lib\site-packages\petl\io\csv_py2.py", line
> 145, in *init*
> f = UTF8Recoder(f, encoding=encoding, errors=errors)
> File "D:\ProgramFiles\python27\lib\site-packages\petl\io\csv_py2.py", line
> 133, in *init*
> self.reader = codec.streamreader(buf, errors=errors)
> TypeError: StreamReader() argument 2 must be string, not None
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/347>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by Alwayslow** [comment]
I  have solve the problem,on windows ,you must append the encoding argument in fromcsv()、tocsv() and so on:
    tocsv(rowiteror_list, 'example.csv', encoding='utf-8')
    tab1_1 = fromcsv('example.csv', encoding='utf-8')
    print look(tab1_1)

**Comment by loadingxys** [comment]
I have met the same question when i was using .display() in "petl Case Study 1 - Comparing Tables"
```
import petl as etl
a = etl.fromtsv('snpdata.csv',encoding='utf-8')
b = etl.fromtsv('popdata.csv',encoding='utf-8')
b_renamed = b.rename({'Chromosome': 'Chr', 
                      'Coordinates': 'Pos', 
                      'Ref. Allele': 'Ref', 
                      'Non-Ref. Allele': 'Nref', 
                      'Derived Allele': 'Der', 
                      'Mutation type': 'Mut', 
                      'Gene': 'GeneId', 
                      'Gene Aliases': 'GeneAlias', 
                      'Gene Description': 'GeneDescr'})
common_fields = ['Chr', 'Pos', 'Ref', 'Nref', 'Der', 'Mut', 'GeneId', 'GeneAlias', 'GeneDescr']
a_common = a.cut(common_fields)
b_common = b_renamed.cut(common_fields)

"""here is a problem !!!"""
print a_common.display(vrepr=repr)
```
and then the error is:
```
Traceback (most recent call last):    print a_common.display(vrepr=repr)
  File "D:\Tools\python\lib\site-packages\petl\util\vis.py", line 575, in display
    encoding=encoding, truncate=truncate)
  File "D:\Tools\python\lib\site-packages\petl\util\vis.py", line 552, in _display_html
    td_styles=td_styles, truncate=truncate)
  File "D:\Tools\python\lib\site-packages\petl\io\html.py", line 66, in tohtml
    f = codec.streamwriter(buf, errors=errors)
TypeError: StreamWriter() argument 2 must be string, not None
```
i tried to add encoding in .display() like this:
```
print a_common.display(vrepr=repr,encoding='utf-8')
```
and then, it returns 'None' 
```
None
[Finished in 1.3s]
```

where is wrong ?
thanks

**Comment by alimanfoo** [comment]
Hi @loadingxys, the display() functions is meant for use within a Jupyter (IPython) notebook, have you tried it there? It generates an HTML representation of a table and then displays it within the notebook. There are some examples here: http://nbviewer.ipython.org/github/alimanfoo/petl/blob/master/repr_html.ipynb

More generally it is annoying that on Windows errors like this arise, I will see if anything can be done to avoid passing in a None encoding.

**Comment by alimanfoo** [comment]
Just to correct, looks like problem is with None value being passed as the 'errors' argument, nothing to do with encodings.

**Comment by alimanfoo** [comment]
I have changed the default value for the `errors` kwarg to 'strict' instead of None, which should hopefully fix issues like this in general. Closing as should prevent the reported errors arising but please re-open if you cannot verify.
