### ISSUE TITLE
Boolean evaluation gotcha in SQLAlchemy

### ISSUE THREAD

**Issue by TimmyCarbone** [alimanfoo/petl#371]
Hey there!

When providing a `metadata` argument in the `to_db(...., create=True, metadata=None)` function with database creation, SQLAlchemy triggers an error:

```
Traceback (most recent call last):
  File "/etl/flows.py", line 178, in ETLFlows
    etl.todb(flows, pgconn, 'flows', metadata=table, create=True, dialect='postgresql', constraints=False)
  File "/env/local/lib/python2.7/site-packages/petl/io/db.py", line 335, in todb
    dialect=dialect, sample=sample)
  File "//env/local/lib/python2.7/site-packages/petl/io/db_create.py", line 225, in create_table
    metadata=metadata, dialect=dialect)
  File "/env/local/lib/python2.7/site-packages/petl/io/db_create.py", line 177, in make_create_table_statement
    metadata=metadata)
  File "/env/local/lib/python2.7/site-packages/petl/io/db_create.py", line 137, in make_sqlalchemy_table
    if not metadata:
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 539, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
```

This is very likely to come from that [SQLAlchemy gotcha](http://docs.sqlalchemy.org/en/latest/changelog/migration_06.html#an-important-expression-language-gotcha).

and there it is : https://github.com/alimanfoo/petl/blob/master/petl/io/db_create.py#L137

This fixed it for me : 
 - Replace `if not metadata:` with `if metadata is not None:`.

I can create a PR later today, let me know if it helps. Not much time for that right now, just wanted to document this.
Hope it helps.

**Comment by TimmyCarbone** [comment]
My bad, I was passing the Table metadata instead of the SQLAlchemy metadata object.

**Comment by alimanfoo** [comment]
No worries, glad it's working ok.

On Mon, Feb 8, 2016 at 11:47 AM, Timothy Carbone <notifications@github.com>
wrote:

> My bad, I was passing the Table metadata instead of the SQLAlchemy
> metadata object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alimanfoo/petl/issues/371#issuecomment-181332323>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721
