### ISSUE TITLE
Allow validation on optional fields

### ISSUE THREAD

**Issue by dusktreader** [alimanfoo/petl#399]
I have some optional fields in my table. I also have some validation constraints that I would like to apply to them if they are defined. Currently, if a field is not defined but a constraint is applied, the following exception is produced:
`petl.errors.FieldSelectionError: selection is not a field or valid field index: 'digital_runtime'`

I would like to be able to apply validation to a field if it exists and ignore the validation constraint if it does not

**Comment by alimanfoo** [comment]
Thanks, this sounds like a useful feature. I don't have time to implement
right now but would be happy to review a PR.

**Comment by dusktreader** [comment]
I'm working on one presently. It's a fairly small change, but I'm making sure to include a couple of unit tests as well

**Comment by dusktreader** [comment]
@alimanfoo i think this issue can be closed now that the pr is merged

**Comment by alimanfoo** [comment]
Thanks
