### ISSUE TITLE
optimized_write deprecation- openpyxl library

### ISSUE THREAD

**Issue by nsepetys** [alimanfoo/petl#438]
Appears _optimized_write_ is deprecated in favor of _write_only_ for the openpyxl library.Workbook initialization. Here are my brief logs:

> [2018-04-08 20:50:39,067] {{base_task_runner.py:98}} INFO - Subtask:   File "/usr/local/airflow/dags/common/excel.py", line 33, in write_xlsx_from_result_set
> [2018-04-08 20:50:39,067] {{base_task_runner.py:98}} INFO - Subtask:     wb = xlsx.toxlsx(result_set, target_xlsx_filename)
> [2018-04-08 20:50:39,067] {{base_task_runner.py:98}} INFO - Subtask:   File "/usr/local/lib/python3.6/site-packages/petl/io/xlsx.py", line 79, in toxlsx
> [2018-04-08 20:50:39,067] {{base_task_runner.py:98}} INFO - Subtask:     wb = openpyxl.Workbook(optimized_write=True, encoding=encoding)
> [2018-04-08 20:50:39,067] {{base_task_runner.py:98}} INFO - Subtask: TypeError: __init__() got an unexpected keyword argument 'optimized_write'

I imagine it'll affect anything under xlsx that uses the openpyxl library. Suggested fix is to use _write_only_ per version 2.4.0 (released 4/1/2016) [release notes](http://openpyxl.readthedocs.io/en/stable/changes.html?highlight=optimized_write#a1-2016-04-11).

**Comment by nsepetys** [comment]
nevermind... I found the [commit ](https://github.com/alimanfoo/petl/commit/7f2017f78d011f5e10f1accdb2f0c6ee22af57cb)that fixed this. I'll try pulling straight from master to get the latest and greatest...

**Comment by alimanfoo** [comment]
Apologies, release long overdue.
