### ISSUE TITLE
can't import tosqlite3

### ISSUE THREAD

**Issue by utbien** [alimanfoo/petl#441]
Running petl on Ubuntu 14

I'm trying to import tosqlite3 from petl but I got the following reaction:
>>> from petl import tosqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name tosqlite3

I'm able to import other functions (for example look)
Solution??
Grtz. Jan

**Comment by alimanfoo** [comment]
Hi @utbien, the tosqlite3() function was removed in version 1.0, you can use todb() instead, more info [here](http://petl.readthedocs.io/en/latest/changes.html#database-extract-load-functions) and [here](http://petl.readthedocs.io/en/latest/io.html#petl.io.db.todb).

**Comment by utbien** [comment]
Thank for the quick response.
